# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import sys
# from . import game_pb2 as game__pb2
import games.game_pb2 as game__pb2


class GamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGameDetail = channel.unary_unary(
                '/pb.Gamer/GetGameDetail',
                request_serializer=game__pb2.GameRequest.SerializeToString,
                response_deserializer=game__pb2.GameResponse.FromString,
                )


class GamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGameDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGameDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameDetail,
                    request_deserializer=game__pb2.GameRequest.FromString,
                    response_serializer=game__pb2.GameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.Gamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Gamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGameDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Gamer/GetGameDetail',
            game__pb2.GameRequest.SerializeToString,
            game__pb2.GameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
