# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: games.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgames.proto\x12\x07\x61\x63\x63ount\x1a\x1bgoogle/protobuf/empty.proto\"\xc0\x01\n\x04Game\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x14\n\x0cstar_content\x18\x04 \x01(\t\x12\x16\n\x0e\x64ownload_times\x18\x05 \x01(\t\x12\x16\n\x0e\x63ontent_rating\x18\x06 \x01(\t\x12\x14\n\x0cintroduction\x18\x07 \x01(\t\x12\x13\n\x0bupdate_time\x18\x08 \x01(\t\x12\r\n\x05genre\x18\t \x01(\t\x12\x0e\n\x06groups\x18\n \x03(\x05\"\x11\n\x0fGameListRequest\"!\n\x13GameRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x88\x02\n\x0eUserController\x12\x33\n\x04List\x12\x18.account.GameListRequest\x1a\r.account.Game\"\x00\x30\x01\x12(\n\x06\x43reate\x12\r.account.Game\x1a\r.account.Game\"\x00\x12\x39\n\x08Retrieve\x12\x1c.account.GameRetrieveRequest\x1a\r.account.Game\"\x00\x12(\n\x06Update\x12\r.account.Game\x1a\r.account.Game\"\x00\x12\x32\n\x07\x44\x65stroy\x12\r.account.Game\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_GAME = DESCRIPTOR.message_types_by_name['Game']
_GAMELISTREQUEST = DESCRIPTOR.message_types_by_name['GameListRequest']
_GAMERETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['GameRetrieveRequest']
Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), {
  'DESCRIPTOR' : _GAME,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:account.Game)
  })
_sym_db.RegisterMessage(Game)

GameListRequest = _reflection.GeneratedProtocolMessageType('GameListRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMELISTREQUEST,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:account.GameListRequest)
  })
_sym_db.RegisterMessage(GameListRequest)

GameRetrieveRequest = _reflection.GeneratedProtocolMessageType('GameRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMERETRIEVEREQUEST,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:account.GameRetrieveRequest)
  })
_sym_db.RegisterMessage(GameRetrieveRequest)

_USERCONTROLLER = DESCRIPTOR.services_by_name['UserController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAME._serialized_start=54
  _GAME._serialized_end=246
  _GAMELISTREQUEST._serialized_start=248
  _GAMELISTREQUEST._serialized_end=265
  _GAMERETRIEVEREQUEST._serialized_start=267
  _GAMERETRIEVEREQUEST._serialized_end=300
  _USERCONTROLLER._serialized_start=303
  _USERCONTROLLER._serialized_end=567
# @@protoc_insertion_point(module_scope)
