# Generated by Django 4.0.5 on 2022-06-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('star_rating', models.CharField(max_length=20)),
                ('download_times', models.CharField(max_length=20)),
                ('content_rating', models.CharField(max_length=20)),
                ('introduction', models.TextField()),
                ('update_time', models.DateTimeField()),
                ('image', models.URLField()),
                ('url', models.URLField()),
                ('apk', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='GamesGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
            ],
        ),
    ]
